import type { StackItem } from '@/components/CardStack';

export const profile = {
  name: 'Neel Kamal',
  title: 'Software Engineer II',
  bio: 'Software Engineer II at Deloitte specializing in .NET Core and enterprise application development within the Tax Transformation Office. Experienced in building scalable backend systems, secure APIs, and cloud-aligned solutions on Azure. Previously worked as a Flutter developer in early-stage startups, delivering production-ready mobile applications with strong focus on performance and user experience.',  location: 'Gurugram, Haryana, India',
  email: 'neelpunia382@gmail.com',
  github: 'https://github.com/neelkamal123-code',
  linkedin: 'https://www.linkedin.com/in/neelpunia/',
  resumeUrl: '/Neel_s_Resume_2026_1.pdf',
  buyMeACoffeeUrl: 'https://buymeacoffee.com/neelkamalpunia',
};

export const experience: StackItem[] = [
  {
    id: 'deloitte', name: 'Deloitte', accent: true,
    sub: 'Software Engineer II', period: 'August 2023 — Present',
    desc: "Promoted from BTA to SDE I and currently SDE II within the Tax Transformation Office. Contributing to the SDT Print Team by developing and optimizing enterprise-grade applications using .NET Core and .NET Framework. Building secure APIs, improving system performance, and supporting scalable, cloud-aligned solutions deployed on Azure with containerized workloads.",
    url: 'https://www2.deloitte.com/in/en.html',
    companyAbout: 'Global consulting and advisory firm helping organizations navigate digital transformation, cybersecurity, AI adoption, and enterprise modernization at scale.',
    tech: ['.NET Core', '.NET Framework', 'Angular', 'Azure', 'Kubernetes', 'SQL Server', 'MongoDB', 'Redis']  },
  {
    id: 'culturecircle', name: 'Culture Circle', accent: false,
    sub: 'Flutter Developer', period: 'November 2022 — February 2023',
    desc: "One of the first engineers to join the early-stage sneaker marketplace startup. Built the initial Flutter application from template to production-ready MVP. Integrated blockchain-based sneaker authentication, implemented real-time updates, optimized app performance, and collaborated closely with backend teams to shape core product architecture.",
    url: 'https://www.culture-circle.com/',
    companyAbout: 'Early-stage sneaker marketplace integrating Web3 tech for authentication and community-driven product discovery.',
    tech: ['Flutter', 'Dart', 'Blockchain', 'Web3', 'Firebase', 'Redis', 'REST APIs', 'Git']  },
  {
    id: 'petmojo',
    name: 'Pet Mojo',
    accent: false,
    sub: 'Flutter Frontend Developer',
    period: 'May 2022 — August 2022',
    desc: "Developed and enhanced the Flutter mobile application for an at-home pet care services platform. Translated Figma designs into responsive UI components, implemented booking flows for pet services, integrated REST APIs, and improved app performance and state management. Collaborated closely with backend and design teams to deliver a seamless user experience.",
    url: 'https://www.petmojo.care/',
    companyAbout: 'Platform connecting pet owners with at-home pet care providers and services.',
    tech: ['Flutter', 'Dart', 'Firebase', 'REST APIs', 'Provider', 'Git', 'Figma']
  },
  {
    id: 'settyl',
    name: 'Settyl',
    accent: false,
    sub: 'Full Stack Flutter Developer',
    period: 'March 2022 â€” May 2022',
    desc: 'Handled regular app updates and feature improvements for the company application. Worked on API integration, state management, backend development with Node.js, and Dio client implementation. Collaborated through GitHub workflows on a daily basis while delivering production-ready changes.',
    url: 'https://www.settyl.com',
    companyAbout: 'Enterprise Business Management Platform focused on S2P, P2P, Domestic, and EXIM workflows. Powered by Lasya AI to automate business operations across web and voice channels, with a mission of inclusive digital growth for all.',
    tech: ['Flutter', 'Dart', 'Node.js', 'REST APIs', 'Dio', 'State Management', 'GitHub']
  }
];

export const education: StackItem[] = [
  {
    id: 'mait',
    name: 'Maharaja Agrasen Institute of Technology',
    accent: false,
    sub: 'Bachelor of Technology (B.Tech)',
    period: 'May 2019 — 2023',
    desc: 'Pursuing B.Tech with focus on software engineering, data structures, and application development. Actively involved in building real-world projects and strengthening problem-solving skills.',
    url: 'https://mait.ac.in/',
    tech: ['Data Structures', 'OOP', 'DBMS', 'Software Engineering']
  },
  {
    id: 'aps12',
    name: 'Army Public School Shankar Vihar',
    accent: false,
    sub: 'Class XII',
    period: 'May 2018 — May 2019',
    desc: 'Completed senior secondary education.',
    url: 'https://apsshankarvihar.ac.in/',
    tech: []
  },
  {
    id: 'aps10',
    name: 'Army Public School Shankar Vihar',
    accent: false,
    sub: 'Class X',
    period: 'May 2016 — May 2017',
    desc: 'Completed secondary education.',
    url: 'https://apsshankarvihar.ac.in/',
    tech: []
  }
];
export const projects: StackItem[] = [
  {
    id: 'portfolio',
    name: 'Developer Portfolio',
    accent: true,
    sub: 'Next.js · TypeScript · Tailwind',
    period: '2026 — Present',
    desc: 'Personal developer portfolio showcasing professional experience, certifications, and projects. Built with modern web technologies, featuring dynamic data-driven sections, clean UI design, and optimized performance for fast load times and responsive user experience. Integrated Google Analytics (GA4) for real-time traffic insights and user engagement tracking on production deployments.',
    tech: ['Next.js', 'TypeScript', 'React', 'Tailwind CSS', 'Vercel', 'Google Analytics (GA4)'],
    sourceUrl: 'https://github.com/neelkamal123-code/portfolio',
    demoUrl: '#',
  }, 
  {
    id: 'expense-manager',
    name: 'Expense Manager App',
    accent: true,
    sub: 'Flutter · Provider · Shared Preferences',
    period: '2019',
    desc: 'A Flutter-based mobile application for tracking daily expenses with clean UI and efficient state management using Provider. Implements local data persistence using Shared Preferences, enabling users to add, categorize, and manage expenses seamlessly with real-time updates.',
    tech: ['Flutter', 'Dart', 'Provider', 'Shared Preferences', 'Material UI', 'State Management'],
    sourceUrl: 'https://github.com/neelkamal123-code/flutter_expense_manager',
    demoUrl: '#',
  },  
  {
    id: 'pingpong',
    name: 'Ping Pong Game',
    accent: true,
    sub: 'Python · Turtle Graphics',
    period: '2026 — Present',
    desc: 'A 2-player desktop Ping Pong game built using Python Turtle. Includes smooth paddle controls, real-time score tracking, pause/resume, restart, quit shortcuts, center divider UI, and a first-to-7 win system. Gameplay difficulty increases over time with dynamic ball speed scaling after paddle collisions.',
    tech: ['Python', 'Turtle', 'time', 'Git', 'GitHub'],
    sourceUrl: 'https://github.com/neelkamal123-code/python-pingpong',
    demoUrl: '#',
  },
  {
    id: 'djangoecom',
    name: 'Django E-commerce',
    accent: true,
    sub: 'Full-Stack Web Store',
    period: 'Django · Python · SQLite',
    desc: 'A Django-based e-commerce app with product catalog, cart management, customer auth, checkout-to-order flow, and admin CRUD support.',
    tech: ['Python', 'Django', 'SQLite', 'Bootstrap', 'Pillow'],
    sourceUrl: 'https://github.com/neelkamal123-code/python-django-ecommerce',
    demoUrl: null,
  },
  {
  id: 'pythonchatbot',
  name: 'Python AI Chatbot',
  accent: true,
  sub: 'Local LLM Terminal Chat',
  period: 'Python · LangChain · Ollama',
  desc: 'A terminal-based AI chatbot built in Python with LangChain and Ollama, featuring session chat memory plus clear/exit commands for smooth local conversations.',
  tech: ['Python', 'LangChain', 'Ollama', 'dotenv'],
  sourceUrl: 'https://github.com/neelkamal123-code/python-chatbot',
  demoUrl: null,
  },
  {
    id: 'bytesbrain',
    name: 'BytesBrain',
    accent: true,
    sub: 'Python Face Recognition Attendance + Smart Whiteboard',
    period: '2021',
    desc: 'Built during a hackathon, BytesBrain combines live face-recognition attendance with a hand-controlled virtual whiteboard. The system recognizes students from a camera feed, logs attendance automatically, supports quick quiz launch, and exports attendance to an Excel file.',
    tech: ['Python', 'Face Recognition', 'OpenCV', 'NumPy', 'Tkinter', 'Excel Export'],
    sourceUrl: 'https://github.com/neelkamal123-code/CIS-HACK/tree/main',
    demoUrl: 'https://drive.google.com/file/d/1Uu13LYEFEUq6g1xuglFiWwmY13qUACz2/view',
  },

];

export const certifications: StackItem[] = [
    {
    id: 'az400',
    name: 'Microsoft Certified: DevOps Engineer Expert',
    accent: true,
    sub: 'Microsoft',
    period: 'Feb 2026',
    desc: 'Validates expertise in designing and implementing DevOps practices on Azure, including CI/CD, source control, infrastructure, and monitoring.',
    tech: ['Azure DevOps', 'GitHub Actions', 'CI/CD', 'Infrastructure as Code', 'Monitoring'],
    url: 'https://learn.microsoft.com/api/credentials/share/en-us/NeelKamal-6249/8EA3B2152C8292E9?sharingId=6C0688093092B22D',
  },
  {
    id: 'az204',
    name: 'Microsoft Certified: Azure Developer Associate',
    accent: true,
    sub: 'Microsoft',
    period: 'July 2025',
    desc: 'Validates expertise in designing, building, testing, and maintaining cloud applications and services on Microsoft Azure.',
    tech: ['Azure App Services', 'Azure Functions', 'Cosmos DB', 'Storage', 'Azure AD'],
    url: 'https://learn.microsoft.com/api/credentials/share/en-us/NeelKamal-6249/56A3A27298D0755C?sharingId=6C0688093092B22D',
  },
  {
    id: 'ai102',
    name: 'Microsoft Certified: Azure AI Engineer Associate',
    accent: true,
    sub: 'Microsoft',
    period: 'February 2026',
    desc: 'Demonstrates skills in designing and implementing AI solutions using Azure Cognitive Services, Azure OpenAI, and ML services.',
    tech: ['Azure AI Services', 'Cognitive Services', 'Azure OpenAI', 'ML Solutions'],
    url: 'https://learn.microsoft.com/api/credentials/share/en-us/NeelKamal-6249/2C84E1553222784E?sharingId=6C0688093092B22D',
  },
  {
    id: 'az900',
    name: 'Microsoft Certified: Azure Fundamentals',
    accent: true,
    sub: 'Microsoft',
    period: 'April 2025',
    desc: 'Foundational certification covering Azure cloud concepts, core services, security, compliance, and pricing.',
    tech: ['Cloud Concepts', 'Azure Core Services', 'Security', 'Governance'],
    url: 'https://learn.microsoft.com/api/credentials/share/en-us/NeelKamal-6249/34D5D0A9EAF50288?sharingId=6C0688093092B22D',
  },
  {
    id: 'pythonml',
    name: 'Python for ML/AI',
    accent: true,
    sub: 'Elite Techno Group',
    period: '2021',
    desc: 'Hands-on training in Python programming with focus on machine learning fundamentals and AI concepts.',
    tech: ['Python', 'NumPy', 'Pandas', 'Machine Learning'],
    url: 'https://drive.google.com/file/d/164C8rK7BTl9-VoSJbx6M0jkF-RzwG2T1/view?usp=sharing',
  },
  {
    id: 'j2ee',
    name: 'Java J2EE Certification',
    accent: true,
    sub: 'Wipro',
    period: 'September 2022',
    desc: 'Training and certification covering Java, J2EE architecture, servlets, JSP, and enterprise application development concepts.',
    tech: ['Java', 'J2EE', 'Servlets', 'JSP'],
    url: 'https://drive.google.com/file/d/1lGtgtOTIn0Z1DHG78UMMeA9NZFc3Sp44/view?usp=sharing',
  },
  {
    id: 'cis-hackathon-2021',
    name: 'Code Innovation Series Hackathon - Certificate of Participation',
    accent: true,
    sub: 'GitHub x IncubateIND',
    period: 'May 2021',
    desc: 'Participated in the Code Innovation Series Hackathon and built BytesBrain, a Python-based face-recognition attendance system with a smart whiteboard and quiz-assist workflow for classroom sessions.',
    tech: ['Hackathon', 'Python', 'Face Recognition', 'OpenCV', 'Innovation'],
    url: 'https://drive.google.com/file/d/1u0mtGnk23LkZPW2sj1weB6nKu34YChpC/view?usp=sharing',
  },
];

export const skills = [
  { name: '.NET Core / .NET Framework', level: 90 },
  { name: 'C# & OOP', level: 88 },
  { name: 'Azure Cloud', level: 85 },
  { name: 'REST APIs & Backend Development', level: 88 },
  { name: 'SQL Server / DBMS', level: 82 },
  { name: 'Flutter & Dart', level: 80 },
  { name: 'Python', level: 75 },
  { name: 'Microservices Architecture', level: 78 },
  { name: 'Docker / Kubernetes (Basics)', level: 70 },
];
